import { useState } from 'react'
import Head from 'next/head'
import Header from '@/components/Header'
import light from '@/styles/theme/light'
import dark from '@/styles/theme/dark'
import MainView from '@/components/MainView'
import SearchInput from '@/components/SearchInput'
import CharacterList from '@/components/CharacterList'
import { ThemeProvider } from 'styled-components'
import CharacterCard from '@/components/CharacterCard'
import GlobalStyle from '../styles/global';

export default function Home() {
  const [theme, setTheme] = useState(light);

  const toggleTheme = () => {
    setTheme(theme.title === 'light' ? dark : light);
  }

  return (
    <ThemeProvider theme={theme}>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header toggleTheme={toggleTheme} />
      <MainView>
        <SearchInput />
        <CharacterList>
          <CharacterCard>1</CharacterCard>
          <CharacterCard>2</CharacterCard>
          <CharacterCard>3</CharacterCard>
          <CharacterCard>4</CharacterCard>
        </CharacterList>
      </MainView>
    </ThemeProvider>
  )
}
