import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import { useState } from 'react'
import light from '@/styles/theme/light'
import dark from '@/styles/theme/dark'
import { ThemeProvider } from 'styled-components'
import GlobalStyle from '../styles/global';


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [theme, setTheme] = useState(light);

  const toggleTheme = () => {
    setTheme(theme.title === 'light' ? dark : light);
  }

  return (
    <ThemeProvider theme={theme}>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header toggleTheme={toggleTheme} />
      <main className={`${styles.main} ${inter.className}`} >
        oi
      </main>
    </ThemeProvider>
  )
}
